[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
itertools = "0.13.0"
lazy_static = "1.5.0"
log = "0.4.22"
num-traits = "0.2.19"
regex = "1.11.1"
strum = { version = "0.26.3", features = ["derive"] }

[profile.release]
debug = true
