[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
regex = "1.11.1"
strum = {version= "0.26.3", features = ["derive"]}

[profile.release]
debug = true
